name = "ai-nes-gpt5"

# Cloudflare Pages output directory (Vite root outputs here)
pages_build_output_dir = "src/host/browser/dist"

# Note: Build command must be set in the Cloudflare Pages UI to:
#   npm run build:host
# The Pages wrangler.toml does not support a [build] section.

