name = "ai-nes-gpt5" # optional, not used by Pages

# Cloudflare Pages output directory (Vite root outputs here)
pages_build_output_dir = "src/host/browser/dist"

[build]
# Use the browser host build (do not run `npm run build` which type-checks entire repo)
command = "npm run build:host"
